# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qmv8mVrCSAdVi3inKoVxMpREi5Vs6L5T
"""

import numpy as np
notas = np.array([7.5, 8.0, 9.0, 5.5, 6.5])
print(notas)

# exibir o primeiro elemento do array
print(notas[0])
print(notas[1])
print(notas[-1])

# exibir a maior nota
print("maior nota: ", notas.max())

# exibir menor nota
print("menor nota: ", notas.min())

# exibir a media das notas
print("Médias das notas: ", notas.mean())

# exibir a soma das notas
print("a soma das notas é: ", notas.sum())

# multiplicação de valores
print(notas * 2)

# calcular desconto percentual
print(notas * 0.90)

# criar um array
idades = np.array([15, 16, 18, 21, 30, 17, 45])

# verificar quais idades são >= 18 anos
print(idades >= 18)

# filtrar as idades >= 18
print(idades[idades >= 18])
print(np.where(idades >= 18))
index = np.where(idades >= 18)
print(idades[index])

# ordenar o array
print(np.sort(idades))

# ordenando de forma reversa
print(np.sort(idades)[::-1])